name: Extract and Release

on:
    workflow_dispatch:
        inputs:
            ROM_URL:
                description: "ROM_URL"
                default: "https://builds.paranoidandroid.co/aospa-uvite-beta-davinci-20240415-image.zip"
            DEVICE_NAME:
                description: "DEVICE_NAME"
                default: "Asus Zenfone 9"
            EXTRACTED_FILES:
                description: "EXTRACTED_FILES"
                default: "vendor.img"

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install tools
              run: |
                  sudo apt-get update
                  sudo apt-get install -y simg2img unzip e2fsprogs

            - name: Download ROM file and rename
              run: |
                  curl -LO ${{ github.event.inputs.ROM_URL }}
                  downloaded_file=$(ls -t | head -n 1)  # Lấy file mới nhất
                  mv "$downloaded_file" rom.zip

            - name: Extract ROM
              run: |
                  unzip rom.zip -d extracted_rom
                  echo "ZIP_FILE=rom.zip" >> $GITHUB_ENV
                  echo "ZIP_FILE_SHA256=$(sha256sum rom.zip | cut -d' ' -f1)" >> $GITHUB_ENV

            - name: Find vendor.img
              run: |
                  vendor_img_path=$(find extracted_rom -name vendor.img)
                  if [ -z "$vendor_img_path" ]; then
                    echo "vendor.img not found!"
                    exit 1
                  else
                    echo "Found vendor.img at $vendor_img_path"
                  fi
                  echo "VENDOR_IMG=$vendor_img_path" >> $GITHUB_ENV

            - name: Upload vendor.img to Release
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ env.VENDOR_IMG }}
                  asset_name: ${{ github.event.inputs.DEVICE_NAME }}-vendor.img
                  asset_content_type: application/octet-stream

            - name: Clean up
              run: |
                  rm -rf extracted_rom rom.zip
