name: Extract and Upload Vendor.img

on:
    workflow_dispatch:
        inputs:
            ROM_URL:
                description: "ROM_URL"
                default: "https://pixeldrain.com/api/file/StGHtPFc"
            DEVICE_NAME:
                description: "DEVICE_NAME"
                default: "OnePlus 9R "

jobs:
    extract-and-upload:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install tools
              run: |
                  sudo apt-get update
                  sudo apt-get install -y simg2img unzip

            - name: Download ROM file and rename
              run: |
                  curl -LJO ${{ github.event.inputs.ROM_URL }} -o rom.zip

            - name: Extract ROM
              run: |
                  unzip rom.zip -d extracted_rom
                  echo "ZIP_FILE=rom.zip" >> $GITHUB_ENV

            - name: Find vendor.img
              run: |
                  cd extracted_rom
                  vendor_image=$(find . -name "vendor.img")
                  if [ -z "$vendor_image" ]; then
                    echo "::error::vendor.img not found!"
                    exit 1
                  fi
                  echo "Found vendor.img at $vendor_image"
                  cp "$vendor_image" ../vendor.img

            - name: Upload vendor.img to Release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: vendor.img
                  name: ${{ github.event.inputs.DEVICE_NAME }}-vendor-img-${{ github.run_id }}
                  tag_name: ${{ github.run_id }}
                  body: |
                      Device: ${{ github.event.inputs.DEVICE_NAME }}
                      Filename: [${{ env.ZIP_FILE }}](${{ github.event.inputs.ROM_URL }})
                      Extracted file: vendor.img

            - name: Clean up
              run: |
                  rm -rf extracted_rom vendor.img rom.zip
