name: Extract and Release

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "ROM URL"
        default: "https://builds.paranoidandroid.co/aospa-topaz-2-bladerunner_48m-20230820-image.zip"
      DEVICE_NAME:
        description: "Device Name"
        default: "oneplus9"

jobs:
  extract-rom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install 7-Zip
        run: sudo apt-get install -y p7zip-full

      - name: Download ROM file
        run: |
          curl -L ${{ github.event.inputs.ROM_URL }} --output rom.zip
          echo "ROM file downloaded and renamed to rom.zip."

      - name: Extract ROM using 7-Zip
        run: |
          7z x rom.zip -orom_extracted
          echo "ROM extracted to rom_extracted directory."

      - name: Extract vendor.img using 7-Zip
        run: |
          cd rom_extracted
          7z x vendor.img -ovendor_extracted
          echo "Extracted vendor.img to vendor_extracted directory."

      - name: Locate build.prop and extract device info
        run: |
          cd vendor_extracted
          if [ -f build.prop ]; then
            echo "build.prop found. Extracting device info..."
            MANUFACTURER=$(grep -oP 'ro.product.manufacturer=\K.*' build.prop)
            MODEL=$(grep -oP 'ro.product.model=\K.*' build.prop)
            FINGERPRINT=$(grep -oP 'ro.build.fingerprint=\K.*' build.prop)
            BRAND=$(grep -oP 'ro.product.brand=\K.*' build.prop)
            PRODUCT=$(grep -oP 'ro.product.name=\K.*' build.prop)
            DEVICE=$(grep -oP 'ro.product.device=\K.*' build.prop)
            SECURITY_PATCH=$(grep -oP 'ro.build.version.security_patch=\K.*' build.prop)
            FIRST_API_LEVEL=$(grep -oP 'ro.product.first_api_level=\K.*' build.prop)

            # Tạo file JSON
            echo "{
              \"MANUFACTURER\": \"$MANUFACTURER\",
              \"MODEL\": \"$MODEL\",
              \"FINGERPRINT\": \"$FINGERPRINT\",
              \"BRAND\": \"$BRAND\",
              \"PRODUCT\": \"$PRODUCT\",
              \"DEVICE\": \"$DEVICE\",
              \"SECURITY_PATCH\": \"$SECURITY_PATCH\",
              \"FIRST_API_LEVEL\": \"$FIRST_API_LEVEL\"
            }" > extracted_info.json

            echo "Extracted info saved to extracted_info.json."
          else
            echo "::error:: build.prop not found!"
            exit 1
          fi

      - name: Upload extracted_info.json to Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: extracted_info.json
          name: ${{ github.event.inputs.DEVICE_NAME }}-extracted-info-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
