name: Extract and Release

on:
    workflow_dispatch:
        inputs:
            ROM_URL:
                description: "ROM_URL"
                default: "https://builds.paranoidandroid.co/aospa-topaz-2-bladerunner_48m-20230820-image.zip"
            DEVICE_NAME:
                description: "DEVICE_NAME"
                default: "oneplus9"
            EXTRACTED_FILES:
                description: "EXTRACTED_FILES"
                default: "build.prop"

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install tools
              run: |
                  sudo apt-get update
                  sudo apt-get install -y simg2img unzip e2fsprogs

            - name: Download ROM file and rename
              run: |
                  curl -LO ${{ github.event.inputs.ROM_URL }}
                  downloaded_file=$(ls -t | head -n 1)  # Lấy file mới nhất
                  mv "$downloaded_file" rom.zip

            - name: Extract ROM
              run: |
                  unzip rom.zip -d extracted_rom
                  echo "ZIP_FILE=rom.zip" >> $GITHUB_ENV
                  echo "ZIP_FILE_SHA256=$(sha256sum rom.zip | cut -d' ' -f1)" >> $GITHUB_ENV

            - name: Find and convert vendor.img
              run: |
                  cd extracted_rom
                  vendor_image=$(find . -name "vendor.img")
                  if [ -z "$vendor_image" ]; then
                    echo "::error::vendor.img not found!"
                    exit 1
                  fi
                  # Kiểm tra xem có phải sparse image hay không
                  if file "$vendor_image" | grep -q "sparse"; then
                    echo "Converting sparse image..."
                    simg2img "$vendor_image" vendor_raw.img
                  else
                    echo "Not a sparse image, copying directly."
                    cp "$vendor_image" vendor_raw.img
                  fi
            
                  # Kiểm tra loại hệ thống file
                  file_type=$(file vendor_raw.img)
                  echo "File type: $file_type"
            
                  # Chỉ mount nếu là ext4 hoặc loại file hệ thống hợp lệ
                  if echo "$file_type" | grep -q "ext4"; then
                    mkdir vendor_mount
                    sudo mount -o loop vendor_raw.img vendor_mount
                  else
                    echo "::error::Unsupported file system type!"
                    exit 1
                  fi

            - name: Extract build.prop
              run: |
                  cp vendor_mount/build.prop build.prop
                  cat build.prop

            - name: Upload build.prop to Release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: build.prop
                  name: ${{ github.event.inputs.DEVICE_NAME }}-build-prop-${{ github.run_id }}
                  tag_name: ${{ github.run_id }}
                  body: |
                      Device: ${{ github.event.inputs.DEVICE_NAME }}
                      Filename: [${{ env.ZIP_FILE }}](${{ github.event.inputs.ROM_URL }})
                      Extracted file: build.prop
                      SHA256: ${{ env.ZIP_FILE_SHA256 }}

            - name: Clean up
              run: |
                  sudo umount vendor_mount
                  rm -rf extracted_rom vendor_mount vendor_raw.img build.prop rom.zip
