name: Extract Vendor

on:
    workflow_dispatch:
        inputs:
            ROM_URL:
                description: "ROM_URL"
                default: "https://builds.paranoidandroid.co/aospa-uvite-beta-davinci-20240415-image.zip"
            DEVICE_NAME:
                description: "DEVICE_NAME"
                default: "Asus Zenfone 9"
            EXTRACTED_FILES:
                description: "EXTRACTED_FILES"
                default: "vendor.img"

jobs:
    extract-and-release:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install tools
              run: |
                  sudo apt-get update
                  sudo apt-get install -y unzip

            - name: Download ROM file
              run: |
                  curl -LJO ${{ github.event.inputs.ROM_URL }}
                  downloaded_file=$(basename "${{ github.event.inputs.ROM_URL }}")
                  mv "$downloaded_file" rom.zip

            - name: Extract vendor.img
              run: |
                  unzip rom.zip "$EXTRACTED_FILES" -d extracted_files/
                  ls extracted_files/

            - name: Upload vendor.img to Release
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: extracted_files/${{ github.event.inputs.EXTRACTED_FILES }}
                  asset_name: ${{ github.event.inputs.DEVICE_NAME }}-vendor.img
                  asset_content_type: application/octet-stream

            - name: Clean up
              run: |
                  rm -rf extracted_files rom.zip
